version: "3"
services:
  #Node Service
  node:
    image: node:10.16.0-jessie
    container_name: flashcard-node
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: node
      SERVICE_TAGS: dev
      #these are read out of global .env
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
    working_dir: /usr/app
    ports:
      - "3011:${APP_PORT}"
    volumes:
      - ./app:/usr/app
    entrypoint: ./on-start.sh
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
