version: "3"
services:
  #Node Service
  node:
    build: 
      context: ./
      args:
        AWS_KEY: ${AWS_KEY}
        AWS_SECRET: ${AWS_SECRET}
        AWS_REGION: ${AWS_REGION}
    container_name: flashcard-node
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: node
      SERVICE_TAGS: dev
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      AWS_SECRET: ${AWS_SECRET}
      AWS_KEY: ${AWS_KEY}
    working_dir: /usr/app
    ports:
      - "3011:${APP_PORT}"
    volumes:
      - ./app:/usr/app
    entrypoint: ./on-start.sh
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
