/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a2749d45-41ff-434b-b278-ff39e475f506",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lkmJ1RgS3",
    "aws_user_pools_web_client_id": "6q14nphvbfsm6rulbhlm5i1pik",
    "oauth": {},
    "aws_user_files_s3_bucket": "cck-flashcard142451-docker",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://ffq5cqn4ingwrljamv5kzix3ba.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
